[package]
name = "vm"
version = "0.1.0"
authors = ["Mark Barbone <mark.l.barbone@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"
